In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.10.0'

In [6]:
weights = tf.Variable(initial_value=tf.random.normal([300, 200], stddev=0.5), name='weight', trainable=False)

In [7]:
weights

<tf.Variable 'weight:0' shape=(300, 200) dtype=float32, numpy=
array([[ 4.5945364e-01,  3.2590762e-01,  5.5218810e-01, ...,
         4.2359737e-01, -6.4866304e-01,  4.2431098e-01],
       [ 1.0684656e+00,  6.1648130e-01, -5.1852667e-01, ...,
         1.2624747e-01,  6.5625034e-02,  1.0049391e+00],
       [-7.6762713e-02, -6.6852415e-01,  2.1600330e-01, ...,
         2.3818174e-01,  1.1479932e-01, -8.0208942e-02],
       ...,
       [-5.4134226e-01, -6.3496542e-01,  1.0394981e-01, ...,
         4.5285118e-01,  3.8341087e-01, -7.2879559e-01],
       [-2.5016907e-01,  1.3969873e-01,  1.2404506e-01, ...,
         3.8555944e-01,  6.1234116e-04,  2.5700346e-01],
       [-2.1503206e-02, -3.1262687e-01,  2.1896552e-01, ...,
        -1.0563614e+00, -9.0014285e-01,  2.2931848e-01]], dtype=float32)>

In [19]:
# a = tf.constant(value=[1,2,3,4,5,6])
a = tf.constant(value=[[1,2,3,4,5,6]])
b = tf.constant(value=[[1],[2],[3],[4],[5],[8]])

result = tf.matmul(a, b)
result

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[103]])>

In [23]:
c = tf.constant(3)
c

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
a

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]])>

In [21]:
b

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [8]])>

In [22]:
result

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[103]])>